### ISSUE TITLE
Google Form API ( getValidtors of an item)

### ISSUE THREAD

**Issue by wret36** [googlesamples/apps-script#27]
Hi,

Is there a way to get the current validations I assigned on a item?
Example:
let form = FormApp.openById('1234567890abcdefghijklmnopqrstuvwxyz');
let item = form.addTextItem();
.......
.......
let validations = item.getValidations();

**Comment by grant** [comment]
Currently there is no way to `getValidations`: https://developers.google.com/apps-script/reference/forms/text-item

File Apps Script bugs on the bug tracker instead of this sample repo:
https://developers.google.com/apps-script/support#bugs

This bug also states this issue. You can press the star it to +1 it:
https://issuetracker.google.com/issues/72151985
